version: "3.7"
services:
  db:
    image: mysql:5.7
    network_mode: "host"
    platform: linux/amd64
    container_name: mysql_host
    volumes:
      - ./database:/var/lib/minesql
    environment:
      MYSQL_USER: sbcntruser
      MYSQL_PASSWORD: sbcntrpass
      MYSQL_DATABASE: sbcntrapp
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
  app:
    image: sbcntr-backend:latest
    depends_on:
      - "db"
    container_name: sbcntr-backend
    environment:
      DB_HOST: localhost
      DB_USERNAME: sbcntruser
      DB_PASSWORD: sbcntrpass
      DB_NAME: sbcntrapp
    network_mode: "host"
    ports:
      - "3100:80"
